/** Field / layout module metadata — icons attached in core.js via jsx-runtime. */
export const FIELD_CATALOG_META = [
	{ id: 'name', name: 'Name', category: 'field', columnSpan: 1, description: 'Collect user name' },
	{ id: 'email', name: 'Email', category: 'field', columnSpan: 1, description: 'Collect email address' },
	{ id: 'single-line-text', name: 'Single Line Text', category: 'field', columnSpan: 1, description: 'Short text input' },
	{ id: 'textarea', name: 'Textarea', category: 'field', columnSpan: 2, description: 'Long text input' },
	{ id: 'dropdown', name: 'Dropdown', category: 'field', columnSpan: 1, description: 'Select from options' },
	{ id: 'radio', name: 'Radio', category: 'field', columnSpan: 1, description: 'Single choice' },
	{ id: 'checkbox', name: 'Checkbox', category: 'field', columnSpan: 1, description: 'Multiple choices' },
	{ id: 'phone', name: 'Phone', category: 'field', columnSpan: 1, description: 'Phone number' },
	{ id: 'address', name: 'Address', category: 'field', columnSpan: 2, description: 'Full address' },
	{ id: 'date-time', name: 'Date & Time', category: 'field', columnSpan: 1, description: 'Date picker' },
	{ id: 'password', name: 'Password', category: 'field', columnSpan: 1, description: 'Secure input' },
	{ id: 'website', name: 'Website', category: 'field', columnSpan: 1, description: 'URL field' },
	{ id: 'number', name: 'Number', category: 'field', columnSpan: 1, description: 'Numeric input' },
	{ id: 'file-upload', name: 'File Upload', category: 'field', columnSpan: 2, description: 'Upload files' },
	{ id: 'date', name: 'Date', category: 'field', columnSpan: 1 },
	{ id: 'time', name: 'Time', category: 'field', columnSpan: 1 },
	{ id: 'terms-conditions', name: 'Terms & Conditions', category: 'field', columnSpan: 1 },
	{ id: '1-column', name: '1-Column', category: 'layout', columnSpan: 1, description: 'Full width container' },
	{ id: '2-column', name: '2-Column', category: 'layout', columnSpan: 2, description: 'Half width container' },
	{ id: '3-column', name: '3-Column', category: 'layout', columnSpan: 3, description: 'Three-quarter width' },
	{ id: '4-column', name: '4-Column', category: 'layout', columnSpan: 4, description: 'Full width section' },
	{ id: 'recaptcha', name: 'Google reCAPTCHA', category: 'security', columnSpan: 2, description: 'Bot protection' },
	{ id: 'cloudflare', name: 'Cloudflare Turnstile', category: 'security', columnSpan: 2, description: 'Privacy protection' },
	{ id: 'page-break', name: 'Page/Step Break', category: 'integration', columnSpan: 4, description: 'Multi-step forms' },
];
